### ISSUE TITLE
Not Auto Switching if an AXE is in front of the other tools

### ISSUE THREAD

**Issue by iPollox** [thebombzen/AutoSwitch#6] opened 2017-09-25 06:22 UTC
Using version 5.6.1 for 1.12.1 minecraft, the mod works except for Shovel related blocks, it doesn't want to auto switch to the shovel when trying to dig Grass/Soul Sand/etc

**Comment by thebombzen** [comment] 2017-09-25 06:23
Post a link to a debug log on https://gist.github.com/

**Comment by thebombzen** [comment] 2017-09-25 08:15
If you're wondering how to do that exactly, I've updated instructions on [the main thread](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1278132-thebombzens-mods#ASBugReport).

**Comment by iPollox** [comment] 2017-09-26 05:22
https://gist.github.com/iPollox/13747d67dbba865fba583f865dfad301

I did some more research, seems like when i have an "axe" before the shovel, it doesnt switch to the shovel, but if the shovel is infront of the axe it does switch to the shovel.

E.g [BUG]
Slot 1: Pickaxe
Slot 2: Axe
Slot 3: Shovel

if the shovel is on a slot AFTER an axe it wont switch.

**Comment by thebombzen** [comment] 2017-09-26 07:29
I cannot reproduce this on 1.9.4, 1.10.2, 1.11.2, or 1.12.1. What version of Minecraft are you using? What version of MultiMC? What version of Forge? What other mods are you using?

**Comment by iPollox** [comment] 2017-09-26 23:24
MC: 1.12.1
MultiMC: 0.5.0-945 (Latest stable as of today)
Forge: 14.22.1.2478 (Recommended)
Liteloader

I got quiet a few mods, I'll start disabling some in a second but my list is:
AutoSwith
Better HUD
gammaBright
invTweaks
JourneyMap
Just Enough Items/Resources
LiteModWorldDownloader
Macro KeyBinds
Optifine
Schematica
StatusEffectHUD
Waila/What are we looking at

**Comment by thebombzen** [comment] 2017-09-27 00:52
I'm still not able to reproduce it, but the debug log did point out a bug that might fix your issue. I'm going to attach a test build that I think might fix this issue. If so, I'll include it in the next patch when I update for 1.12.2.

**Comment by thebombzen** [comment] 2017-09-27 00:54
(Github rejects JAR files so I've placed the test jarfile it inside a ZIP.)
[AutoSwitch-test.zip](https://github.com/thebombzen/AutoSwitch/files/1335422/AutoSwitch-test.zip)

**Comment by iPollox** [comment] 2017-09-27 04:09
Seems to be working perfectly now, what was it? 👍

**Comment by thebombzen** [comment] 2017-09-27 07:26
I missed a check for null when checking the item stacks for enchantments.

Resolution: Fixed by a47215453afad4c7aca7fca5a8ff6288f4876788.

**Closed** 2017-09-27 07:27 UTC
Labels: defect, fixed
