### ISSUE TITLE
Using Pickaxe instead of shovel for gravel and dirt

### ISSUE THREAD

**Issue by ZizzyZizzy** [thebombzen/AutoSwitch#8] opened 2017-10-12 05:02 UTC
Pickaxe is Efficiency V, Unbreaking III, Fortune III, Mending
Shovel is Efficiency IV, Unbreaking III, Fortune II, Mending, Curse of Vanishing.

The 1.12.2 version of this mod insists on changing to the Pickaxe when hitting gravel or dirt, when it should pick the shovel.

**Comment by ZizzyZizzy** [comment] 2017-10-12 05:05
Oh, also, a Beacon with Haste II is active. That should not matter; A pickaxe should NEVER be the selected tool for gravel or dirt when there is a pickaxe in the hotbar.

**Comment by Traneptora** [comment] 2017-10-12 06:33
Post a debug log. Please read the FAQ.

**Comment by Traneptora** [comment] 2017-10-12 06:37
However, it seems to me that AutoSwitch is correctly detecting that Fortune III is better than Fortune II, and Fortune works on Gravel, so it's using the Fortune III tool to harvest gravel. This sounds like intended behavior.

**Comment by ZizzyZizzy** [comment] 2017-10-14 02:07
@thebombzen Perhaps, but I would have expected the end goal for mining was speed, not more drops. Also, when mining dirt, that Fortune enchant doesn't matter, so all it does is slow mining down and put unnecessary extra wear on the Pickaxe. 

It takes three strikes to break a dirt block with a Fortune III/Eff VI Pickaxe, and one with the Fortune II/Eff IV shovel. For gravel, that is four strikes to one strike, and this is all under a Haste II beacon coverage. It would actually be more efficient (and lucrative) to hit 4 times as much gravel with the Fortune II shovel and save the wear & tear and time of using the Pickaxe.

**Comment by Traneptora** [comment] 2017-10-14 05:15
When digging dirt it should unambiguously use the shovel. Which is why, again, please send me a debug log.

**Comment by Traneptora** [comment] 2017-11-15 18:39
Log never sent. I'm closing this rather than having it sit open indefinitely. If you'd like to resubmit this bug, re-open a new issue.

**Closed as completed by Traneptora** 2017-11-15 18:39 UTC
Labels: defect, invalid, wontfix
